steps:

- id: "Rodando Testes"
  name: 'golang'
  env:
  - GOPATH=src
  args: ['go', test', '.']

- id: "Rodando script"
  name: 'golang'
  env:
  - GOPATH=src
  args: ['go', run', '.']

- id: "Rodando Build"
  name: 'golang'
  env:
  - GOPATH=src
  args: ['go', build', '.']

images:
  - 'gcr.io/$PROJECT_ID/go-soma:latest'
  - 'gcr.io/$PROJECT_ID/go-soma:0.0.1'
