steps:

- id: "Rodando Testes"
  name: 'golang'
  env:
  - GOPATH=./src
  args: ['test']

- id: "Rodando script"
  name: 'golang'
  env:
  - GOPATH=./src
  args: ['run']

- id: "Rodando Build"
  name: 'golang'
  env:
  - GOPATH=./src
  args: ['build']

images:
  - 'gcr.io/$PROJECT_ID/go-soma:latest'
  - 'gcr.io/$PROJECT_ID/go-soma:0.0.1'
