steps:

# - id: "Definindo o PATH"
#   name: golang
#   args: ['mod', 'init', '.']

- id: "Rodando Testes"
  name: golang
  args: ['test', '.']

- id: "Rodando Build"
  name: golang
  args: ['build', '-ldflags', '"-s -w"', '.']

images:
  - 'gcr.io/$PROJECT_ID/go-soma:latest'
  - 'gcr.io/$PROJECT_ID/go-soma:0.0.1'
